[".config/awesome/lain"]
    type = "git-repo"
    url = "https://github.com/lcpz/lain.git"
    refreshPeriod = "168h"
[".config/awesome/awesome-wm-widgets"]
    type = "git-repo"
    url = "https://github.com/streetturtle/awesome-wm-widgets.git"
    refreshPeriod = "168h"
