# ---------------- #
# mpv user options #
# ---------------- #

# Duration of fade out in ms
fadeduration=500

# Size ratio of the knob handle
seekbarhandlesize=1

# -------------------- #
# ModernX user options #
# -------------------- #

# Prevent OSC from showing on pause
showonpause=no

# Show title in OSC
showtitle=yes

volumecontrol=yes
