# Don't print a new line at the start of the prompt
add_newline = false
# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """
[package]
disabled = true

[golang]
disabled = true

[status]
disabled = false

[cmd_duration]
disabled = true

[buf]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

